const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Tween,
		C3.Behaviors.solid,
		C3.Plugins.Particles,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.PlaygamaBridge,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Behaviors.Sin,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Spritefont2.Acts.MoveToLayer,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Exps.Angle,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.EightDir.Exps.VectorX,
		C3.Behaviors.EightDir.Exps.VectorY,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetY,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Exps.MaxSpeed,
		C3.Behaviors.EightDir.Exps.Acceleration,
		C3.Plugins.System.Acts.Signal,
		C3.Behaviors.EightDir.Exps.Deceleration,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Particles.Acts.MoveToTop,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Particles.Acts.SetTowardPosition,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Particles.Exps.X,
		C3.Plugins.Particles.Exps.Y,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Exps.min,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Particles.Acts.SetZElevation,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Behaviors.EightDir.Exps.Speed,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.Seek,
		C3.Plugins.Audio.Exps.Duration,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Spritefont2.Acts.SetAngle,
		C3.Plugins.Spritefont2.Exps.Angle,
		C3.Plugins.PlaygamaBridge.Exps.PlatformId,
		C3.Plugins.PlaygamaBridge.Acts.SendMessage,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.PlaygamaBridge.Acts.AppendStorageDataSetRequest,
		C3.Plugins.PlaygamaBridge.Acts.SendStorageDataSetRequest,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.PlaygamaBridge.Exps.PlatformLanguage,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.PlaygamaBridge.Acts.AppendStorageDataGetRequest,
		C3.Plugins.PlaygamaBridge.Acts.SendStorageDataGetRequest,
		C3.Plugins.PlaygamaBridge.Cnds.OnStorageDataGetRequestCompleted,
		C3.Plugins.PlaygamaBridge.Cnds.HasStorageData,
		C3.Plugins.System.Exps.float,
		C3.Plugins.PlaygamaBridge.Exps.StorageData,
		C3.Plugins.PlaygamaBridge.Exps.StorageDataAsJSON,
		C3.Plugins.PlaygamaBridge.Acts.CheckAdBlock,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.PlaygamaBridge.Cnds.IsDesktop,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.PlaygamaBridge.Cnds.OnInterstitialClosed,
		C3.Plugins.PlaygamaBridge.Cnds.OnInterstitialFailed,
		C3.Plugins.Browser.Acts.Focus,
		C3.Plugins.PlaygamaBridge.Cnds.OnRewardedClosed,
		C3.Plugins.PlaygamaBridge.Cnds.OnRewardedFailed,
		C3.Plugins.PlaygamaBridge.Cnds.OnRewardedRewarded,
		C3.Plugins.PlaygamaBridge.Acts.ShowRewarded,
		C3.Plugins.PlaygamaBridge.Acts.ShowInterstitial,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.TiledBg.Acts.SetPos
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{BoundToLayout: 0},
	{player: 0},
	{Keyboard: 0},
	{Touch: 0},
	{Pin: 0},
	{saw: 0},
	{ScrollTo: 0},
	{camera: 0},
	{health: 0},
	{pos_x: 0},
	{pos_y: 0},
	{target_x: 0},
	{target_y: 0},
	{jitter: 0},
	{price: 0},
	{level: 0},
	{damage_block: 0},
	{is_upper: 0},
	{Tween: 0},
	{Solid: 0},
	{box: 0},
	{particles_destroying: 0},
	{vint: 0},
	{stick_base: 0},
	{stick_nub: 0},
	{Browser: 0},
	{reference: 0},
	{particles_bubble: 0},
	{water: 0},
	{drop_state: 0},
	{can_pick: 0},
	{rad: 0},
	{pilisos_state: 0},
	{mini_box: 0},
	{inv: 0},
	{id: 0},
	{zone: 0},
	{saw_connector: 0},
	{saw_connector_stick: 0},
	{text_id: 0},
	{text_ru: 0},
	{text_en: 0},
	{Fade: 0},
	{text: 0},
	{fon_tiled: 0},
	{sunlight: 0},
	{start_scale: 0},
	{base_w: 0},
	{base_h: 0},
	{shop_plane: 0},
	{row: 0},
	{Sprite4: 0},
	{button: 0},
	{Sprite5: 0},
	{levels_plane: 0},
	{level_button: 0},
	{Vertical: 0},
	{scroll_max_speed: 0},
	{scrolling: 0},
	{scrolling_speed: 0},
	{scrolling_angle: 0},
	{listat: 0},
	{saw_place: 0},
	{saw_connector_player: 0},
	{ship: 0},
	{sky: 0},
	{Sprite3: 0},
	{go_up: 0},
	{bubble: 0},
	{Sprite2: 0},
	{map_side: 0},
	{path: 0},
	{w: 0},
	{h: 0},
	{pilisos: 0},
	{particles_destroyed: 0},
	{Sprite6: 0},
	{rama: 0},
	{Audio: 0},
	{upgrade_info: 0},
	{Text2: 0},
	{pilisos_text: 0},
	{pilisos_screen: 0},
	{admin: 0},
	{Particles_water: 0},
	{left_right: 0},
	{run: 0},
	{speed: 0},
	{r: 0},
	{g: 0},
	{b: 0},
	{fish: 0},
	{Sprite7: 0},
	{bubble_count: 0},
	{bubbleSpawner: 0},
	{sprite_text: 0},
	{vert_bar: 0},
	{vert_bar_: 0},
	{fix: 0},
	{Particles_upgrade: 0},
	{metka: 0},
	{stage_ava: 0},
	{Sprite: 0},
	{bonus_plane: 0},
	{black_fon: 0},
	{confetty: 0},
	{Particles_confetty: 0},
	{levels_opened: 0},
	{level_block: 0},
	{PlaygamaBridge: 0},
	{loading_bar_rama: 0},
	{loading_bar_green: 0},
	{LocalStorage: 0},
	{level_rama: 0},
	{pause_panel: 0},
	{pause_b: 0},
	{pause_fon: 0},
	{checkbox: 0},
	{strlki: 0},
	{Physics: 0},
	{DestroyOutsideLayout: 0},
	{fish_skelet: 0},
	{fish_particles: 0},
	{sitelock: 0},
	{Sine: 0},
	{hand: 0},
	{tutor_button: 0},
	{time_ad: 0},
	{shop_cooldown: 0},
	{rocket: 0},
	{rocket_flame: 0},
	{rocket_fon: 0},
	{test_btn: 0},
	{DragDrop: 0},
	{listats: 0},
	{box_family: 0},
	{gameplay_state: 0},
	{player_speed: 0},
	{damage: 0},
	{money: 0},
	{language: 0},
	{stage: 0},
	{is_on_water: 0},
	{sound: 0},
	{map_stars: 0},
	{earned_on_map: 0},
	{spent_on_map: 0},
	{game_started: 0},
	{first_start: 0},
	{separator: 0},
	{money_num: 0},
	{count_num: 0},
	{en: 0},
	{ru: 0},
	{v1: 0},
	{v2: 0},
	{camera_speed: 0},
	{water_y: 0},
	{vel_x: 0},
	{vel_y: 0},
	{gravity: 0},
	{radius: 0},
	{distancee: 0},
	{anglee: 0},
	{move_x: 0},
	{move_y: 0},
	{vx: 0},
	{vy: 0},
	{rotate_speed: 0},
	{target_angle: 0},
	{x: 0},
	{y: 0},
	{saw_rotate_speed: 0},
	{point: 0},
	{coef: 0},
	{jitter_value: 0},
	{jitter_speed: 0},
	{any_jitter: 0},
	{h0: 0},
	{r_hp: 0},
	{mult: 0},
	{distance_to_drop_pos: 0},
	{picking_distance: 0},
	{lerp_speed: 0},
	{v0: 0},
	{r_val: 0},
	{return_price: 0},
	{levell: 0},
	{is_collided_with_zone: 0},
	{add_gold: 0},
	{stick_x: 0},
	{stick_y: 0},
	{upgrade_cur_value_4: 0},
	{upgrade_cur_value_5: 0},
	{map_value: 0},
	{not_max: 0},
	{create_stage: 0},
	{is_free: 0},
	{opacity: 0},
	{base_cap: 0},
	{r_cap: 0},
	{base_speed: 0},
	{r_speed: 0},
	{r1: 0},
	{r2: 0},
	{r3: 0},
	{ad_logo_angle: 0},
	{start_speed: 0},
	{end_speed: 0},
	{stage_price: 0},
	{k: 0},
	{block_stage_buttons: 0},
	{index: 0},
	{stop_speed: 0},
	{engine_mix: 0},
	{speed_norm: 0},
	{speedd: 0},
	{pilisos_volume: 0},
	{max_vol: 0},
	{saw_pool: 0},
	{max_saw_pool: 0},
	{box_des_pool: 0},
	{box_des_max_sounds: 0},
	{col_pool: 0},
	{col_max_sounds: 0},
	{fish_max_speed: 0},
	{run_mult: 0},
	{grass: 0},
	{destroy_grass: 0},
	{zoom: 0},
	{block_count_max: 0},
	{block_destroyed_count: 0},
	{pop_up_speed: 0},
	{bonus: 0},
	{inv_save_wait: 0},
	{cloud_unavailable: 0},
	{go_level: 0},
	{is_cloud_loaded: 0},
	{is_pause: 0},
	{restart_menu: 0},
	{audio_state: 0},
	{pl1_1: 0},
	{pl1_2: 0},
	{pl1_3: 0},
	{pl1_4: 0},
	{pl1_5: 0},
	{pl2_1: 0},
	{pl2_2: 0},
	{pl2_3: 0},
	{pl2_4: 0},
	{reward_state: 0},
	{reward_state_id: 0},
	{is_time_ad_menu_opened: 0},
	{time_ad_state: 0},
	{timer_time: 0},
	{cooldown_time: 0},
	{statee: 0},
	{state_id: 0},
	{planet_id: 0},
	{planet_window_opened: 0},
	{sky_color: 0},
	{water_color: 0},
	{block_button: 0}
];

self.InstanceType = {
	player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	saw: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	particles_destroying: class extends self.IParticlesInstance {},
	vint: class extends self.ISpriteInstance {},
	stick_base: class extends self.ISpriteInstance {},
	stick_nub: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	reference: class extends self.ISpriteInstance {},
	particles_bubble: class extends self.IParticlesInstance {},
	water: class extends self.ISpriteInstance {},
	mini_box: class extends self.ISpriteInstance {},
	inv: class extends self.IArrayInstance {},
	zone: class extends self.ISpriteInstance {},
	saw_connector: class extends self.ISpriteInstance {},
	saw_connector_stick: class extends self.ISpriteInstance {},
	text: class extends self.ISpriteFontInstance {},
	fon_tiled: class extends self.ITiledBackgroundInstance {},
	sunlight: class extends self.ISpriteInstance {},
	shop_plane: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	levels_plane: class extends self.ISpriteInstance {},
	level_button: class extends self.ISpriteInstance {},
	listat: class extends self.ISpriteInstance {},
	saw_place: class extends self.ISpriteInstance {},
	saw_connector_player: class extends self.ISpriteInstance {},
	ship: class extends self.ISpriteInstance {},
	sky: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	bubble: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	map_side: class extends self.ITiledBackgroundInstance {},
	path: class extends self.ITiledBackgroundInstance {},
	pilisos: class extends self.ISpriteInstance {},
	particles_destroyed: class extends self.IParticlesInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	rama: class extends self.I9PatchInstance {},
	Audio: class extends self.IInstance {},
	upgrade_info: class extends self.IArrayInstance {},
	Text2: class extends self.ITextInstance {},
	pilisos_text: class extends self.ISpriteFontInstance {},
	pilisos_screen: class extends self.ISpriteInstance {},
	admin: class extends self.ISpriteInstance {},
	Particles_water: class extends self.IParticlesInstance {},
	fish: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	bubbleSpawner: class extends self.ISpriteInstance {},
	sprite_text: class extends self.ISpriteInstance {},
	vert_bar: class extends self.ISpriteInstance {},
	vert_bar_: class extends self.ITiledBackgroundInstance {},
	fix: class extends self.ISpriteInstance {},
	Particles_upgrade: class extends self.IParticlesInstance {},
	metka: class extends self.ISpriteInstance {},
	stage_ava: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	bonus_plane: class extends self.ISpriteInstance {},
	black_fon: class extends self.ISpriteInstance {},
	confetty: class extends self.ISpriteInstance {},
	Particles_confetty: class extends self.IParticlesInstance {},
	levels_opened: class extends self.IArrayInstance {},
	level_block: class extends self.ISpriteInstance {},
	PlaygamaBridge: class extends C3.Plugins.PlaygamaBridge.Instance {},
	loading_bar_rama: class extends self.ISpriteInstance {},
	loading_bar_green: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	level_rama: class extends self.ISpriteInstance {},
	pause_panel: class extends self.ISpriteInstance {},
	pause_b: class extends self.ISpriteInstance {},
	pause_fon: class extends self.ISpriteInstance {},
	checkbox: class extends self.ISpriteInstance {},
	strlki: class extends self.ISpriteInstance {},
	fish_skelet: class extends self.ISpriteInstance {},
	fish_particles: class extends self.IParticlesInstance {},
	sitelock: class extends self.IArrayInstance {},
	hand: class extends self.ISpriteInstance {},
	tutor_button: class extends self.ISpriteInstance {},
	time_ad: class extends self.ISpriteInstance {},
	shop_cooldown: class extends self.IArrayInstance {},
	rocket: class extends self.ISpriteInstance {},
	rocket_flame: class extends self.IParticlesInstance {},
	rocket_fon: class extends self.ISpriteInstance {},
	test_btn: class extends self.ISpriteInstance {},
	listats: class extends self.ISpriteInstance {},
	box_family: class extends self.ISpriteInstance {}
}